### ISSUE TITLE
is there a way to handle different mimetype for same extension

### ISSUE THREAD

**Issue by piaoger** [abonander/mime_guess#28]
there are some extension has two mimetypes, such as：
rtf   application/rtf; text/rtf
sh   application/x-sh; text/x-sh

do we have a way to handle such a case or can we customize the buiitin mimetypes?

**Comment by abonander** [comment]
It'd be trivial to extend each function to return an array/slice of MIME types instead of a single one. 

However, now we have the problem on how to order the types returned, assuming most people are just going to take the first type returned if they only need one.

As a rule of thumb I would tend to say whichever type was registered with the IANA first, which means `text/rtf`would actually come before `application/rtf`, unless the later one explicitly supercedes the former.

**Comment by abonander** [comment]
The new API I've proposed in this comment will support this: https://github.com/abonander/mime_guess/issues/43#issuecomment-458826052
